# Generated by Django 2.2.19 on 2022-12-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20221201_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, help_text='Основной текст поста', null=True, verbose_name='текст'),
        ),
    ]
